### ISSUE TITLE
Themen für Meeting 2021-07-01

### ISSUE THREAD

**Issue by enko** [plus-me/meta#3]
Hosting: Kosten? Politik?

**Comment by ri0t** [comment]
Hosting bedeutet u.a.
- Mailprovider (Oder nur Push notifications? Zumindest, falls der Auth-provider die Authmails übernimmt. Braucht aber auf jeden Fall eine Absenderaddresse)
- Webhosting für das Backend
- Webhosting für das Frontend

**Comment by enko** [comment]
Soll die App eigentlich auch als Web-App laufen?

**Comment by enko** [comment]
Gibt es Zahlen bzw Ideen wie viele Benutzer die App haben wird? Wie sah das 2017 aus?

**Comment by enko** [comment]
Sollen die Tags Freitext sein oder sollen sie vorgegeben sein?

**Comment by enko** [comment]
Amtssprache fürs repo?

**Comment by enko** [comment]
Meeting vorbei 🙂
